language: node_js
node_js: 8
cache: yarn
notifications:
  email: false
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
