language: node_js
node_js: 8
notifications:
  email: false
env:
  global:
    - SSH_IP: 107.170.89.65
    - SSH_USER: root
    - DOCKER_REPOSITORY: jlobos/blog
    - DOCKER_CONTAINER_NAME: blog
services:
  - docker
cache: yarn
before_deploy:
  - curl -sSL https://get.docker.com/ | sh
  - docker version
  - docker build -t ${DOCKER_REPOSITORY} .
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
  - docker push ${DOCKER_REPOSITORY}
  - openssl aes-256-cbc -K $encrypted_e02ba6df3dde_key -iv $encrypted_e02ba6df3dde_iv -in .deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - echo -e "Host deploy\nHostName ${SSH_IP}\nUser ${SSH_USER}\nStrictHostKeyChecking no" > ~/.ssh/config
  - ssh deploy docker pull ${DOCKER_REPOSITORY}
  - ssh deploy "if docker ps -a --format={{.Names}} | grep -q ${DOCKER_CONTAINER_NAME}; then docker rm -f ${DOCKER_CONTAINER_NAME}; fi"
deploy:
  provider: script
  script: ssh deploy docker run -d --name ${DOCKER_CONTAINER_NAME} ${DOCKER_REPOSITORY}
  skip_cleanup: true
  on:
    branch: master
